"""new fields in user model

Revision ID: 377ef75fe526
Revises: ee8674d4c280
Create Date: 2020-05-24 14:16:35.749462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377ef75fe526'
down_revision = 'ee8674d4c280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=144), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
