"""empty message

Revision ID: d283cff74c13
Revises: a509dfb27104
Create Date: 2020-05-28 18:00:25.530850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd283cff74c13'
down_revision = 'a509dfb27104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    op.drop_column('comment', 'reply_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('reply_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
