"""Added title to posts

Revision ID: d6dae5e9ed9f
Revises: d4c07ffbe635
Create Date: 2020-05-25 20:15:55.707655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dae5e9ed9f'
down_revision = 'd4c07ffbe635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
